navigator.vendorSub = 
navigator.productSub = 20030107
navigator.vendor = Google Inc.
navigator.maxTouchPoints = 0
navigator.hardwareConcurrency = 4
navigator.appCodeName = Mozilla
navigator.appName = Netscape
navigator.appVersion = 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
navigator.platform = Win32
navigator.product = Gecko
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
navigator.language = en-US
navigator.languages = en-US,en,hi
navigator.onLine = true
navigator.cookieEnabled = true
navigator.doNotTrack = null
navigator.geolocation = [object Geolocation]
navigator.mediaDevices = [object MediaDevices]
navigator.plugins = [object PluginArray]
navigator.mimeTypes = [object MimeTypeArray]
navigator.webkitTemporaryStorage = [object DeprecatedStorageQuota]
navigator.webkitPersistentStorage = [object DeprecatedStorageQuota]
navigator.serviceWorker = [object ServiceWorkerContainer]
navigator.getBattery = function getBattery() { [native code] }
navigator.sendBeacon = function sendBeacon() { [native code] }
navigator.getGamepads = function getGamepads() { [native code] }
navigator.webkitGetUserMedia = function webkitGetUserMedia() { [native code] }
navigator.javaEnabled = function javaEnabled() { [native code] }
navigator.vibrate = function vibrate() { [native code] }
navigator.requestMIDIAccess = function requestMIDIAccess() { [native code] }
navigator.credentials = [object CredentialsContainer]
navigator.permissions = [object Permissions]
navigator.presentation = [object Presentation]
navigator.getUserMedia = function getUserMedia() { [native code] }
navigator.registerProtocolHandler = function registerProtocolHandler() { [native code] }
navigator.unregisterProtocolHandler = function unregisterProtocolHandler() { [native code] }
navigator.storage = [object StorageManager]
navigator.requestMediaKeySystemAccess = function () { [native code] }
If you like this page, why not donate a little bit of money to help me pay my bills 